//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cliente_Dulceria_WS.Producto_Service {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfAnyType", Namespace="http://tempuri.org/", ItemName="anyType")]
    [System.SerializableAttribute()]
    public class ArrayOfAnyType : System.Collections.Generic.List<object> {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Productos_VO", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class Productos_VO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int Id_productoField;
        
        private int Categoria_IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreField;
        
        private int PrecioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MarcaField;
        
        private int CantidadField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CaducidadField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int Id_producto {
            get {
                return this.Id_productoField;
            }
            set {
                if ((this.Id_productoField.Equals(value) != true)) {
                    this.Id_productoField = value;
                    this.RaisePropertyChanged("Id_producto");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=1)]
        public int Categoria_Id {
            get {
                return this.Categoria_IdField;
            }
            set {
                if ((this.Categoria_IdField.Equals(value) != true)) {
                    this.Categoria_IdField = value;
                    this.RaisePropertyChanged("Categoria_Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Nombre {
            get {
                return this.NombreField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreField, value) != true)) {
                    this.NombreField = value;
                    this.RaisePropertyChanged("Nombre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public int Precio {
            get {
                return this.PrecioField;
            }
            set {
                if ((this.PrecioField.Equals(value) != true)) {
                    this.PrecioField = value;
                    this.RaisePropertyChanged("Precio");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string Marca {
            get {
                return this.MarcaField;
            }
            set {
                if ((object.ReferenceEquals(this.MarcaField, value) != true)) {
                    this.MarcaField = value;
                    this.RaisePropertyChanged("Marca");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=5)]
        public int Cantidad {
            get {
                return this.CantidadField;
            }
            set {
                if ((this.CantidadField.Equals(value) != true)) {
                    this.CantidadField = value;
                    this.RaisePropertyChanged("Cantidad");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string Caducidad {
            get {
                return this.CaducidadField;
            }
            set {
                if ((object.ReferenceEquals(this.CaducidadField, value) != true)) {
                    this.CaducidadField = value;
                    this.RaisePropertyChanged("Caducidad");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="Producto_Service.productos_ServicesSoap")]
    public interface productos_ServicesSoap {
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento parametros del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetProductos", ReplyAction="*")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Cliente_Dulceria_WS.Producto_Service.ArrayOfAnyType))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Cliente_Dulceria_WS.Producto_Service.Productos_VO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Cliente_Dulceria_WS.Producto_Service.Productos_VO[]))]
        Cliente_Dulceria_WS.Producto_Service.GetProductosResponse GetProductos(Cliente_Dulceria_WS.Producto_Service.GetProductosRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetProductos", ReplyAction="*")]
        System.Threading.Tasks.Task<Cliente_Dulceria_WS.Producto_Service.GetProductosResponse> GetProductosAsync(Cliente_Dulceria_WS.Producto_Service.GetProductosRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetProductosRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetProductos", Namespace="http://tempuri.org/", Order=0)]
        public Cliente_Dulceria_WS.Producto_Service.GetProductosRequestBody Body;
        
        public GetProductosRequest() {
        }
        
        public GetProductosRequest(Cliente_Dulceria_WS.Producto_Service.GetProductosRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetProductosRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Cliente_Dulceria_WS.Producto_Service.ArrayOfAnyType parametros;
        
        public GetProductosRequestBody() {
        }
        
        public GetProductosRequestBody(Cliente_Dulceria_WS.Producto_Service.ArrayOfAnyType parametros) {
            this.parametros = parametros;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetProductosResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetProductosResponse", Namespace="http://tempuri.org/", Order=0)]
        public Cliente_Dulceria_WS.Producto_Service.GetProductosResponseBody Body;
        
        public GetProductosResponse() {
        }
        
        public GetProductosResponse(Cliente_Dulceria_WS.Producto_Service.GetProductosResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetProductosResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Cliente_Dulceria_WS.Producto_Service.Productos_VO[] GetProductosResult;
        
        public GetProductosResponseBody() {
        }
        
        public GetProductosResponseBody(Cliente_Dulceria_WS.Producto_Service.Productos_VO[] GetProductosResult) {
            this.GetProductosResult = GetProductosResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface productos_ServicesSoapChannel : Cliente_Dulceria_WS.Producto_Service.productos_ServicesSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class productos_ServicesSoapClient : System.ServiceModel.ClientBase<Cliente_Dulceria_WS.Producto_Service.productos_ServicesSoap>, Cliente_Dulceria_WS.Producto_Service.productos_ServicesSoap {
        
        public productos_ServicesSoapClient() {
        }
        
        public productos_ServicesSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public productos_ServicesSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public productos_ServicesSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public productos_ServicesSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Cliente_Dulceria_WS.Producto_Service.GetProductosResponse Cliente_Dulceria_WS.Producto_Service.productos_ServicesSoap.GetProductos(Cliente_Dulceria_WS.Producto_Service.GetProductosRequest request) {
            return base.Channel.GetProductos(request);
        }
        
        public Cliente_Dulceria_WS.Producto_Service.Productos_VO[] GetProductos(Cliente_Dulceria_WS.Producto_Service.ArrayOfAnyType parametros) {
            Cliente_Dulceria_WS.Producto_Service.GetProductosRequest inValue = new Cliente_Dulceria_WS.Producto_Service.GetProductosRequest();
            inValue.Body = new Cliente_Dulceria_WS.Producto_Service.GetProductosRequestBody();
            inValue.Body.parametros = parametros;
            Cliente_Dulceria_WS.Producto_Service.GetProductosResponse retVal = ((Cliente_Dulceria_WS.Producto_Service.productos_ServicesSoap)(this)).GetProductos(inValue);
            return retVal.Body.GetProductosResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Cliente_Dulceria_WS.Producto_Service.GetProductosResponse> Cliente_Dulceria_WS.Producto_Service.productos_ServicesSoap.GetProductosAsync(Cliente_Dulceria_WS.Producto_Service.GetProductosRequest request) {
            return base.Channel.GetProductosAsync(request);
        }
        
        public System.Threading.Tasks.Task<Cliente_Dulceria_WS.Producto_Service.GetProductosResponse> GetProductosAsync(Cliente_Dulceria_WS.Producto_Service.ArrayOfAnyType parametros) {
            Cliente_Dulceria_WS.Producto_Service.GetProductosRequest inValue = new Cliente_Dulceria_WS.Producto_Service.GetProductosRequest();
            inValue.Body = new Cliente_Dulceria_WS.Producto_Service.GetProductosRequestBody();
            inValue.Body.parametros = parametros;
            return ((Cliente_Dulceria_WS.Producto_Service.productos_ServicesSoap)(this)).GetProductosAsync(inValue);
        }
    }
}
