//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cliente_Dulceria_WS.Venta_Service {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfAnyType", Namespace="http://tempuri.org/", ItemName="anyType")]
    [System.SerializableAttribute()]
    public class ArrayOfAnyType : System.Collections.Generic.List<object> {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Ventas_VO", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class Ventas_VO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int Id_ventaField;
        
        private int Persona_IdField;
        
        private int Empresa_IdField;
        
        private double SubTotalField;
        
        private double DescuentoField;
        
        private double TotalField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int Id_venta {
            get {
                return this.Id_ventaField;
            }
            set {
                if ((this.Id_ventaField.Equals(value) != true)) {
                    this.Id_ventaField = value;
                    this.RaisePropertyChanged("Id_venta");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int Persona_Id {
            get {
                return this.Persona_IdField;
            }
            set {
                if ((this.Persona_IdField.Equals(value) != true)) {
                    this.Persona_IdField = value;
                    this.RaisePropertyChanged("Persona_Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public int Empresa_Id {
            get {
                return this.Empresa_IdField;
            }
            set {
                if ((this.Empresa_IdField.Equals(value) != true)) {
                    this.Empresa_IdField = value;
                    this.RaisePropertyChanged("Empresa_Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public double SubTotal {
            get {
                return this.SubTotalField;
            }
            set {
                if ((this.SubTotalField.Equals(value) != true)) {
                    this.SubTotalField = value;
                    this.RaisePropertyChanged("SubTotal");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=4)]
        public double Descuento {
            get {
                return this.DescuentoField;
            }
            set {
                if ((this.DescuentoField.Equals(value) != true)) {
                    this.DescuentoField = value;
                    this.RaisePropertyChanged("Descuento");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=5)]
        public double Total {
            get {
                return this.TotalField;
            }
            set {
                if ((this.TotalField.Equals(value) != true)) {
                    this.TotalField = value;
                    this.RaisePropertyChanged("Total");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="Venta_Service.ventas_ServicesSoap")]
    public interface ventas_ServicesSoap {
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento HelloWorldResult del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        Cliente_Dulceria_WS.Venta_Service.HelloWorldResponse HelloWorld(Cliente_Dulceria_WS.Venta_Service.HelloWorldRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        System.Threading.Tasks.Task<Cliente_Dulceria_WS.Venta_Service.HelloWorldResponse> HelloWorldAsync(Cliente_Dulceria_WS.Venta_Service.HelloWorldRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento parametros del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetVentas", ReplyAction="*")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Cliente_Dulceria_WS.Venta_Service.ArrayOfAnyType))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Cliente_Dulceria_WS.Venta_Service.Ventas_VO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Cliente_Dulceria_WS.Venta_Service.Ventas_VO[]))]
        Cliente_Dulceria_WS.Venta_Service.GetVentasResponse GetVentas(Cliente_Dulceria_WS.Venta_Service.GetVentasRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetVentas", ReplyAction="*")]
        System.Threading.Tasks.Task<Cliente_Dulceria_WS.Venta_Service.GetVentasResponse> GetVentasAsync(Cliente_Dulceria_WS.Venta_Service.GetVentasRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorld", Namespace="http://tempuri.org/", Order=0)]
        public Cliente_Dulceria_WS.Venta_Service.HelloWorldRequestBody Body;
        
        public HelloWorldRequest() {
        }
        
        public HelloWorldRequest(Cliente_Dulceria_WS.Venta_Service.HelloWorldRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class HelloWorldRequestBody {
        
        public HelloWorldRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorldResponse", Namespace="http://tempuri.org/", Order=0)]
        public Cliente_Dulceria_WS.Venta_Service.HelloWorldResponseBody Body;
        
        public HelloWorldResponse() {
        }
        
        public HelloWorldResponse(Cliente_Dulceria_WS.Venta_Service.HelloWorldResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class HelloWorldResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string HelloWorldResult;
        
        public HelloWorldResponseBody() {
        }
        
        public HelloWorldResponseBody(string HelloWorldResult) {
            this.HelloWorldResult = HelloWorldResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetVentasRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetVentas", Namespace="http://tempuri.org/", Order=0)]
        public Cliente_Dulceria_WS.Venta_Service.GetVentasRequestBody Body;
        
        public GetVentasRequest() {
        }
        
        public GetVentasRequest(Cliente_Dulceria_WS.Venta_Service.GetVentasRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetVentasRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Cliente_Dulceria_WS.Venta_Service.ArrayOfAnyType parametros;
        
        public GetVentasRequestBody() {
        }
        
        public GetVentasRequestBody(Cliente_Dulceria_WS.Venta_Service.ArrayOfAnyType parametros) {
            this.parametros = parametros;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetVentasResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetVentasResponse", Namespace="http://tempuri.org/", Order=0)]
        public Cliente_Dulceria_WS.Venta_Service.GetVentasResponseBody Body;
        
        public GetVentasResponse() {
        }
        
        public GetVentasResponse(Cliente_Dulceria_WS.Venta_Service.GetVentasResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetVentasResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Cliente_Dulceria_WS.Venta_Service.Ventas_VO[] GetVentasResult;
        
        public GetVentasResponseBody() {
        }
        
        public GetVentasResponseBody(Cliente_Dulceria_WS.Venta_Service.Ventas_VO[] GetVentasResult) {
            this.GetVentasResult = GetVentasResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ventas_ServicesSoapChannel : Cliente_Dulceria_WS.Venta_Service.ventas_ServicesSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ventas_ServicesSoapClient : System.ServiceModel.ClientBase<Cliente_Dulceria_WS.Venta_Service.ventas_ServicesSoap>, Cliente_Dulceria_WS.Venta_Service.ventas_ServicesSoap {
        
        public ventas_ServicesSoapClient() {
        }
        
        public ventas_ServicesSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ventas_ServicesSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ventas_ServicesSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ventas_ServicesSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Cliente_Dulceria_WS.Venta_Service.HelloWorldResponse Cliente_Dulceria_WS.Venta_Service.ventas_ServicesSoap.HelloWorld(Cliente_Dulceria_WS.Venta_Service.HelloWorldRequest request) {
            return base.Channel.HelloWorld(request);
        }
        
        public string HelloWorld() {
            Cliente_Dulceria_WS.Venta_Service.HelloWorldRequest inValue = new Cliente_Dulceria_WS.Venta_Service.HelloWorldRequest();
            inValue.Body = new Cliente_Dulceria_WS.Venta_Service.HelloWorldRequestBody();
            Cliente_Dulceria_WS.Venta_Service.HelloWorldResponse retVal = ((Cliente_Dulceria_WS.Venta_Service.ventas_ServicesSoap)(this)).HelloWorld(inValue);
            return retVal.Body.HelloWorldResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Cliente_Dulceria_WS.Venta_Service.HelloWorldResponse> Cliente_Dulceria_WS.Venta_Service.ventas_ServicesSoap.HelloWorldAsync(Cliente_Dulceria_WS.Venta_Service.HelloWorldRequest request) {
            return base.Channel.HelloWorldAsync(request);
        }
        
        public System.Threading.Tasks.Task<Cliente_Dulceria_WS.Venta_Service.HelloWorldResponse> HelloWorldAsync() {
            Cliente_Dulceria_WS.Venta_Service.HelloWorldRequest inValue = new Cliente_Dulceria_WS.Venta_Service.HelloWorldRequest();
            inValue.Body = new Cliente_Dulceria_WS.Venta_Service.HelloWorldRequestBody();
            return ((Cliente_Dulceria_WS.Venta_Service.ventas_ServicesSoap)(this)).HelloWorldAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Cliente_Dulceria_WS.Venta_Service.GetVentasResponse Cliente_Dulceria_WS.Venta_Service.ventas_ServicesSoap.GetVentas(Cliente_Dulceria_WS.Venta_Service.GetVentasRequest request) {
            return base.Channel.GetVentas(request);
        }
        
        public Cliente_Dulceria_WS.Venta_Service.Ventas_VO[] GetVentas(Cliente_Dulceria_WS.Venta_Service.ArrayOfAnyType parametros) {
            Cliente_Dulceria_WS.Venta_Service.GetVentasRequest inValue = new Cliente_Dulceria_WS.Venta_Service.GetVentasRequest();
            inValue.Body = new Cliente_Dulceria_WS.Venta_Service.GetVentasRequestBody();
            inValue.Body.parametros = parametros;
            Cliente_Dulceria_WS.Venta_Service.GetVentasResponse retVal = ((Cliente_Dulceria_WS.Venta_Service.ventas_ServicesSoap)(this)).GetVentas(inValue);
            return retVal.Body.GetVentasResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Cliente_Dulceria_WS.Venta_Service.GetVentasResponse> Cliente_Dulceria_WS.Venta_Service.ventas_ServicesSoap.GetVentasAsync(Cliente_Dulceria_WS.Venta_Service.GetVentasRequest request) {
            return base.Channel.GetVentasAsync(request);
        }
        
        public System.Threading.Tasks.Task<Cliente_Dulceria_WS.Venta_Service.GetVentasResponse> GetVentasAsync(Cliente_Dulceria_WS.Venta_Service.ArrayOfAnyType parametros) {
            Cliente_Dulceria_WS.Venta_Service.GetVentasRequest inValue = new Cliente_Dulceria_WS.Venta_Service.GetVentasRequest();
            inValue.Body = new Cliente_Dulceria_WS.Venta_Service.GetVentasRequestBody();
            inValue.Body.parametros = parametros;
            return ((Cliente_Dulceria_WS.Venta_Service.ventas_ServicesSoap)(this)).GetVentasAsync(inValue);
        }
    }
}
